### ISSUE TITLE
Fix service port in Openshift template of toggles-service

### ISSUE THREAD

**Issue by xcoulon** [openshiftio/openshift.io#1861]
there's an inconsistency in the name/port combo of the service for `toggles-service`:
````
  spec:
    ports:
      - name: "8080"
        protocol: TCP
        port: 80
        targetPort: 8080
````
the `name` should be `80`
