### ISSUE TITLE
Che workspaces deployments created with a bogus memory limit

### ISSUE THREAD

**Issue by jfchevrette** [openshiftio/openshift.io#1864]
Che workspaces are currently being created with a bogus memory limit.

```
resources:
  limits:
    memory: 2576980377600m
  requests:
    memory: 1100Mi
```
