### ISSUE TITLE
Deployments API endpoint for "per pod quota request"

### ISSUE THREAD

**Issue by andrewazores** [openshiftio/openshift.io#3388]
Parent: https://openshift.io/openshiftio/openshiftio/plan/detail/2240

# Task

The Deployments API should expose an endpoint that can be queried for the amount of resource quota that will be consumed by one pod of a specific deployment. For example, for an OSIO Quickstart application, a single pod consumes 1 Core and 512MB of RAM. These figures should be query-able given a space ID, environment name, and application name.

**Comment by ebaron** [comment]
When defining a custom resource limit for an application via `src/main/fabric8/deployment.yml`, this limit appears in the pod template for a deployment config:
```yaml
        "template": {
            [...]
            "spec": {
                "containers": [
                    {
                        "name": "vertx",
                        [...]
                        "resources": {
                            "limits": {
                                "memory": "250Mi"
                            }
                        },
                        [...]
```
If no resource limit customization is present, there will be no resources element specified in the pod template. The per-container defaults can be queried using the LimitRange API [1]. To determine the total needed by one extra pod, we should sum up the resource limits for each container in the pod template, substituting the default when absent.

[1] https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#limitrange-v1-core
