### ISSUE TITLE
Jenkins namespace is wrongly asking for 2Gi of ram

### ISSUE THREAD

**Issue by pradeepto** [openshiftio/openshift.io#3450]
While it limits itself to 512Mi [1], and content cache also only limits
to 512Mi, the namespace is blocking 2Gi of ram.

This puts our scale at risk and effectively halves the total Jenkins we
are able to run in the cluster ( not really, since overcommit and
rounding / scheduling issues kick in ), but we should fix this and
ensure the namespace only calls for 1Gi and 2 Cpu's.

Note that the mapping works as 512Mi to 1 core, so make sure all limits
are set in that ratio, even the Jenkins deployment, which is currently
set to 2 Core for 512Mi, it should be 1 core.

[1]
https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/apps/jenkins/src/main/fabric8/openshift-deployment.yml

[2]
https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/apps/content-repository/src/main/fabric8/content-repository-deployment.yml#L38

[3]
https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/packages/fabric8-tenant-jenkins-quotas-oso/src/main/fabric8/compute-resources-rq.yml#L8

**Comment by pradeepto** [comment]
@jaseemabid 's reply ...

There are 2 pods in the user-jenkins namespace by default and they both take 512Mi ram and 1 cpu each.
While we run a build, there is one more pod in alive with 2 containers and they are,


image: 'fabric8/maven-builder:v9ff62e0'              | name: maven | cpu: 1250m | memory: 640Mi
image: 'fabric8/jenkins-slave-base-centos7:vb0268ae' | name: jnlp  | cpu: 500m  | memory: 256Mi

The namespace might be using more than 1G because of the extra containers that are alive while the build is running. Now those numbers (640 and 1250) looks specific and set like that for a reason. Do we really want to change this the day before summit?

**Comment by maxandersen** [comment]
is this not in prod now or ?

**Comment by containscafeine** [comment]
@maxandersen not yet, https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/88 breaks everything. We need to find the underlying issue.

**Comment by pradeepto** [comment]
@maxandersen @kbsingh I think this PR shouldn't be merged. We shouldn't touch this with a 100 foot pod.

@piyush1594 has tested this and told me that "every" build fails for him when he tests with this PR. 

We need more extensive debugging and understanding before we merge this. :-1: to merge this  PR before summit.

**Comment by mmclanerh** [comment]
can we get an update here on this sev-1?

**Comment by piyush1594** [comment]
Please go through the discussion on the pull request https://github.com/fabric8-services/fabric8-tenant-jenkins/pull/88

**Comment by krishnapaparaju** [comment]
@pbergene , here is the current status:  @jaseemabid has tried out reducing RAM and service does not come up. @jaseemabid, can you please add more details...

**Comment by jaseemabid** [comment]
Just before the summit, @containscafeine and I tried to lower the resource utilization of the Jenkins master and that led to the instance not coming up correctly several times in a row. Since there were no code changes, I think we might be running the service close to the minimum requirements already. 

This is indeed costing us money, but is definitely not preventing users from using the service hence we should drop the SEV1. We would save even more money if we ship Build.Next on time rather than debug Jenkins resource utilization, so IMHO this should not be a P0 either. 

PS: Its _really painful_ to debug these issues on prod with so many moving pieces and limited account privileges. It really is. The build team would rather do something more meaningful and look forward to Next than be forever dealing with this. 

Thoughts @maxandersen ?

**Comment by krishnapaparaju** [comment]
@jaseemabid would be rather useful to focus the comments to this specific issue. @jaseemabid would be great if you can specify what is blocking you ? service not coming up with lower limits ?

cc @pbergene

**Comment by jaseemabid** [comment]
@krishnapaparaju Yes, service is not coming up with lower limits and its not worth fixing.

**Comment by maxandersen** [comment]
@jaseemabid no matter if there is build.next or not we still need to grok resource usage and limits. Thus figuring out this issue is key imo.

As discussed in this issue and on PR would we not be better of keeping memory as is and reduce the pod count ? This would allow one build to start with enough memory and then other builds would be queued.

**Comment by krishnapaparaju** [comment]
@maxandersen ,  #2729 restricts more than one tenant build at any given point of time.. This is WIP..

cc @hrishin

**Comment by krishnapaparaju** [comment]
@jaseemabid did you try out  'lower limits' (no change in RAM, go from 2 to 1 cores) and  service not coming up with these lower limits ? Please confirm...

**Comment by krishnapaparaju** [comment]
Assigning to @piyush1594

**Comment by krishnapaparaju** [comment]
Current status: Not tried yet lowering cores (2 to 1) keeping the RAM size intact. @piyush1594 can you please try out this combination.

cc @jfchevrette

**Comment by jfchevrette** [comment]
FYI on openshift online free tier, memory "request" is computed by the platform as 60% of the memory "limit" specified.

Additionally, the CPU limit as well as request are also computed based on memory numbers
 - 512Mi RAM (limit) corresponds to 1 core of CPU (limit)
 - 1 core of CPU (limit) results in a CPU "request" of 60m (millicores)

So technically, you would only need to specify a memory limit in the container resource definition and the rest is going to be set/overridden by the platform

**Comment by jfchevrette** [comment]
@jaseemabid I was able to update my jenkins namespace quota and unidle jenkins and content-repository and run a build to completion.

**quota: compute-resources**
```
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  scopes:
  - NotTerminating
status:
  hard:
    limits.cpu: "2"
    limits.memory: 1Gi
  used:
    limits.cpu: "2"
    limits.memory: 1Gi
```

Which as you can see is utilized to 100% when content-repository and jenkins are running.

There is also the **compute-resources-timebound** quota which is consumed when running the jenkins-slave and the s2i pods because both are considered Terminating pods (they are deployed with an activeDeadlineSeconds)

This is a bit out of scope of this issue but here are the details for the timebound quota as a FYI

Once jenkins-slave and s2i pods are started, the **compute-resources-timebound** quota status looks like this
```
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 2Gi
  scopes:
  - Terminating
status:
  hard:
    limits.cpu: "4"
    limits.memory: 2Gi
  used:
    limits.cpu: 2750m
    limits.memory: 1408M
```

**jenkins-slave pod resources (2 containers)**
```
name: maven
resources:
      limits:
        cpu: 1250m
        memory: 640Mi
      requests:
        cpu: 75m
        memory: 384Mi

name: jnlp
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 30m
        memory: 153Mi
```

**s2i pod (3 containers)**
```
name: sti-build
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 60m
        memory: 307Mi

name: git-clone
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 60m
        memory: 307Mi

name: manage-dockerfile
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 60m
        memory: 307Mi
```
