### ISSUE TITLE
Jenkins is idled during build

### ISSUE THREAD

**Issue by ljelinkova** [openshiftio/openshift.io#4503]
##### Issue Overview
The e2e tests are failing because Jenkins is idled during the pipeline build (both prod and prod-preview)

##### Expected Behaviour
The pipeline should finish successfully and after that I should be able to see Jenkins log. 
##### Current Behaviour
The pipeline either does not finish at all and when I click the View log link I can see that Jenkins is idled. Or the pipeline finishes successfully but when I click the View log link I do not see the log only that Jenkins is idled. 
##### Additional Information
The issue can occur on different stages of pipeline. There is one common pattern - the View log link is present and when I click on it it shows Jenkins idled screen. 

_Example_
Build started and View log link is present. This step times out in e2e jobs. 
![build_started](https://user-images.githubusercontent.com/2078072/47715463-2b767000-dc40-11e8-92b8-e5ccbc32a3e4.png)

After opening link to Jenkins log it shows idled Jenkins page. 
![idled_jenkins](https://user-images.githubusercontent.com/2078072/47715474-2fa28d80-dc40-11e8-85bb-aa6d92cc5171.png)

Jenkins logs
This is Jenkins log before the tests - you can see that Jenkins is running
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/3378/oc-jenkins-logs-before-all.txt

This is Jenkins log when test fails - Jenkins is not running (is terminating)
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-beta/3378/oc-jenkins-logs.txt

**Comment by ljelinkova** [comment]
This issue might be related to
https://github.com/openshiftio/openshift.io/issues/4456
https://github.com/openshiftio/openshift.io/issues/4436

**Comment by ljelinkova** [comment]
This is one example of failed build on prod.
![osio](https://user-images.githubusercontent.com/2078072/47723567-0dffd100-dc55-11e8-9ce7-e17ec3fccb6f.png)
Idled Jenkins
![jenkins](https://user-images.githubusercontent.com/2078072/47723577-12c48500-dc55-11e8-9f83-fc7ff0e54e95.png)

Logs before tests (note that the jenkins container is running)
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1284/oc-jenkins-logs-before-all.txt

Logs after tests (note that new jenkins container is just starting)
http://artifacts.ci.centos.org/devtools/e2e/devtools-test-e2e-openshift.io-smoketest-us-east-1a-beta/1284/oc-jenkins-logs.txt

**Comment by ppitonak** [comment]
@stevengutz please make sure that somebody is assigned, this is nr. 1 reason of failing tests on prod-preview

**Comment by stevengutz** [comment]
@sthaha @pradeepto Another P1 bug affecting the E2E tests.  Please take a look at this one ASAP.

**Comment by sthaha** [comment]
@ppitonak can you please give us the following details? 

- how frequent is this? always?
- time in UTC when the build was started so that we can corroborate with kibana logs 
- are you able to reproduce this locally?  if so, steps we can follow to reproduce it?
- how long does the build take? 
- when does the build start ( all time in UTC)

The attached logs do not tell us when the build started 

In the example above I don't see that a build has started at all leading me to believe that jenkins wasn't even running and there could be mutliple cause including openshift not starting jenkins. 

Before
```
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-30T06:54:00Z
    lastUpdateTime: 2018-10-30T06:54:00Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available

  - lastTransitionTime: 2018-10-30T06:54:01Z
    lastUpdateTime: 2018-10-30T06:54:01Z
    message: replication controller "jenkins-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
```
After
```
  conditions:
  - lastTransitionTime: 2018-10-30T06:54:01Z
    lastUpdateTime: 2018-10-30T06:54:01Z
    message: replication controller "jenkins-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing

  - lastTransitionTime: 2018-10-30T07:44:53Z
    lastUpdateTime: 2018-10-30T07:44:53Z
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
```

From before and after all I can gauge is that Jenkins was running for close to `50mins`. Usually a Jenkins is allowed max of 45 mins and if there are builds that are on-going it will be allowed 45 mins since the time it started. 

what i don't know is if any build got started before the jenkins was idled.
