### ISSUE TITLE
Import code flow: Start workspace from Che devfile 

### ISSUE THREAD

**Issue by sbose78** [openshiftio/openshift.io#4538]
If the repo has a Che devfile, the imported repo should use the devfile to start a workspace.
See https://github.com/eclipse/che/issues/11549

**Comment by ibuziuk** [comment]
We had a call where @skabashnyuk and @mshaposhnik presented early version of `devfile`. Basically, from implementation perspective support of `devfile` in osio flow should be pretty easy to implement. che-starter could detect `devfile` in the repository and send `POST /api/devfile` request to Che server with `devfile` definition in the body e.g.:

```
---
version: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic.git'
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
commands:
  - name: run
    attributes:
      runType: sequential
    actions:
      - type: exec
        tool: theia-ide
        command: mvn spring-boot:run
        workdir: /projects/petclinic
```

This would create a  `petclinic-dev-environment` workspace with defined sidecars containers / commands.
