### ISSUE TITLE
Use the upstream openshift-login plugin

### ISSUE THREAD

**Issue by piyush-garg** [openshiftio/openshift.io#4608]
Right now, we are using(https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/plugins/openshift-login.jpi) the fork(https://github.com/fabric8-jenkins/jenkins-openshift-login-plugin) of upstream login plugin(https://github.com/openshift/jenkins-openshift-login-plugin) in our Jenkins image for a single change(https://github.com/fabric8-jenkins/jenkins-openshift-login-plugin/commit/3c21a257a88925a311d948e16c0e9599f36d9f98).

We need to do rebase, build and update sometime according to the patches required for Jenkins version.

Previously this (Role's ACL) was not configurable but now from the upstream release version v1.0.10, this has been made configurable. PR which implements this is https://github.com/openshift/jenkins-openshift-login-plugin/pull/45

You need to add a configmap named openshift-jenkins-login-plugin-config which contains info about which ACL will be assigned to which role and so on like
```
data:
    Credentials-Create: admin
    Credentials-Delete: admin
    Credentials-ManageDomains: admin
    Credentials-Update: admin
    Credentials-View: admin,edit,view
    Job-Build: admin,edit
    Job-Cancel: admin,edit
    Job-Configure: admin,edit
    Job-Create: admin,edit
    Job-Delete: admin,edit
    Job-Discover: admin,edit,view
    Job-Read: admin,edit,view
    Job-Workspace: admin,edit
    Overall-Administer: admin
    Overall-Read: admin,edit,view
    Overall-RunScripts: admin,edit
    Run-Delete: admin
    Run-Update: admin
    SCM-Tag: admin,edit
    Slave-Configure: admin
    Slave-Delete: admin
    View-Configure: admin
    View-Create: admin
    View-Delete: admin
```

More details in README.md here https://github.com/openshift/jenkins-openshift-login-plugin#openshift-role-to-jenkins-permission-mapping

Task is to move from fork to upstream login plugin
