### ISSUE TITLE
Codebases page should also list BuildConfigs from OpenShift which have a Che stack annotation

### ISSUE THREAD

**Issue by joshuawilson** [openshiftio/openshift.io#928]
_From @jstrachan on April 10, 2017 14:33_

Folks can create apps via the Space wizard, via the OpenShift console or via `oc`. They appear on the Builds/Pipeline UI. However they don't show up in Codebases; so there's no way to open Che from that page for created projects.

For now we should combine the data from the Planner and the BuildConfig resources in the users default OpenShift Namespace.
e.g. an example BuildConfig created via the Forge/Obsidian wizard looks like this
```yaml
metadata:
  annotations:
    che.fabric8.io/stack: vert.x
    jenkins.openshift.org/disable-sync-create-on: jenkins
    jenkins.openshift.org/generated-by: jenkins
    jenkins.openshift.org/job-path: jstrachan/demovertx15/master
  creationTimestamp: null
  name: demovertx15
spec:
  nodeSelector: null
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/jstrachan/demovertx15.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
```

From there we can see the `spec.source.git.uri` and branch: `spec.source.git.master` together with the Che stack `metadata.annotations.['che.fabric8.io/stack']` which in this case is vertx

_Copied from original issue: fabric8-ui/fabric8-ui#599_
