### ISSUE TITLE
Recurring/intermittent issue - pipeline is not created - no pipeline information is shown to user

### ISSUE THREAD

**Issue by ldimaggi** [openshiftio/openshift.io#999]
See attached screenshot and Jenkins log - after a new quickstart is created - a pipeline is not created for the project.

Steps to recreate:
* Reset user environment
* Create new space
* Create new quickstart project

**Comment by ldimaggi** [comment]
[jenkins-1-log.txt](https://github.com/openshiftio/openshift.io/files/1321161/jenkins-1-log.txt)
![194_testsep211505990189712_pipeline_promote_fail](https://user-images.githubusercontent.com/642621/30696338-4a86c772-9ea9-11e7-8d0d-a16371692440.png)

**Comment by jstrachan** [comment]
is there a BuildConfig created in your namespace? if so could you do `oc export bc` and attach it please?

**Comment by ldimaggi** [comment]
The EE test found this bug - screenshot is here:
http://artifacts.ci.centos.org/devtools/e2e/194_testsep211505990189712_pipeline_promote_fail.png

**Comment by jstrachan** [comment]
it'd be nice if the E2E tests exported BC / Build along with `oc get deploy -n $(ID)-stage; oc get pod -n $(ID)-stage` etc to help diagnose issues

**Comment by ldimaggi** [comment]
```
oc export bc
apiVersion: v1
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      che.fabric8.io/stack: vert.x
      jenkins.openshift.org/disable-sync-create-on: jenkins
      jenkins.openshift.org/generated-by: jenkins
      jenkins.openshift.org/job-path: osiotestmachine/testsep211505997897684/master
    creationTimestamp: null
    labels:
      space: testsep211505997897684
    name: testsep211505997897684
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/osiotestmachine/testsep211505997897684.git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      che.fabric8.io/stack: spring-boot
      jenkins.openshift.org/disable-sync-create-on: jenkins
      jenkins.openshift.org/generated-by: jenkins
      jenkins.openshift.org/job-path: osiotestmachine/testsep211505997912903/master
    creationTimestamp: null
    labels:
      space: testsep211505997912903
    name: testsep211505997912903
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/osiotestmachine/testsep211505997912903.git
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
  status:
    lastVersion: 0
kind: List
metadata: {}
```
